#!/bin/bash
sudo apt install adb -y
sudo apt install anjuta -y
sudo apt install apache2 -y
sudo apt install audacity -y
sudo apt install bb -y
sudo apt install billard-gl -y
sudo apt install bind9-host -y
sudo apt install bleachbit -y
sudo apt install blender -y
sudo apt install blinken -y
sudo apt install bzip2 -y
sudo apt install ca-certificates -y
sudo apt install catdoc -y
sudo apt install chrome-remote-desktop -y
sudo apt install chrome-token-signing-policy -y
sudo apt install cmake -y
sudo apt install cmatrix -y
sudo apt install cowsay -y
sudo apt install elinks -y
sudo apt install ethtool -y
sudo apt install fastboot -y
sudo apt install ffmpeg -y
sudo apt install ffmpegthumbs -y
sudo apt install filelight -y
sudo apt install filezilla -y
sudo apt install firefox-locale-en -y
sudo apt install firefox-locale-et -y
sudo apt install flake8 -y
sudo apt install font-manager -y
sudo apt install fortune-mod -y
sudo apt install ftp -y
sudo apt install geogebra -y
sudo apt install git -y
sudo apt install glade -y
sudo apt install gnome-disk-utility -y
sudo apt install gnome-screensaver -y
sudo apt install gnome-terminal -y
sudo apt install google-chrome-stable -y
sudo apt install gparted -y
sudo apt install grep -y
sudo add-apt-repository ppa:danielrichter2007/grub-customizer -y
sudo apt update
sudo apt install grub-customizer -y
sudo apt install gtk-recordmydesktop -y
sudo apt install gweled -y
sudo apt install gzip -y
sudo apt install hdparm -y
sudo apt install htop -y
sudo apt install inkscape -y
sudo apt install inxi -y
sudo apt install joystick -y
sudo apt install k3b -y
sudo apt install kate -y
sudo apt install kcalc -y
sudo apt install kdenlive -y
sudo apt install kmail -y
sudo apt install ktorrent -y
sudo apt install kubuntu-restricted-addons -y
sudo apt install libreoffice-base -y
sudo apt install libreoffice-calc -y
sudo apt install libreoffice-impress -y
sudo apt install libreoffice-writer -y
sudo apt install libsane-extras -y
sudo apt install lolcat -y
sudo apt install lxappearance -y
sudo apt install mysql-server -y
sudo apt install nano -y
sudo apt install neofetch -y
sudo apt install neon-desktop -y
sudo apt install net-tools -y
sudo apt install nfoview -y
sudo apt install nmap -y
sudo apt install nplan -y
sudo apt install ntfs-3g -y
sudo apt install nvidia-driver-435 -y
sudo apt install obs-studio -y
sudo apt install openshot -y
sudo apt install openssh-client -y
sudo apt install openssh-server -y
sudo apt install openssl -y
sudo apt install p7zip -y
sudo apt install p7zip-full -y
sudo apt install pavucontrol -y
sudo apt install pciutils -y
sudo apt install pcmanfm -y
sudo apt install pcsx2 -y
sudo apt install php -y
sudo apt install php-mysql -y
sudo apt install pinta -y
sudo apt install piper -y
sudo apt install playonlinux -y
sudo apt install python-apt -y
sudo apt install python-gi-dev -y
sudo apt install python-glade2 -y
sudo apt install python-pip -y
sudo apt install python-tk -y
sudo apt install python3 -y
sudo apt install python3-apt -y
sudo apt install python3-commandnotfound -y
sudo apt install python3-dbus -y
sudo apt install python3-distro-info -y
sudo apt install python3-gdbm -y
sudo apt install python3-gi -y
sudo apt install python3-minimal -y
sudo apt install python3-pip -y
sudo apt install python3-tk -y
sudo apt install python3-update-manager -y
sudo apt install python3-yaml -y
sudo apt install python3.6 -y
sudo apt install python3.6-minimal -y
sudo apt install samba -y
sudo apt install sane -y
sudo apt install sane-utils -y
sudo apt install simple-scan -y
sudo apt install sl -y
sudo apt install subtitleeditor -y
sudo apt install supertuxkart -y
sudo apt install synaptic -y
sudo apt install system-config-samba -y
sudo apt install telnet -y
sudo apt install textdraw -y
sudo apt install thunar -y
sudo apt install thunderbird -y
sudo apt install timeshift -y
sudo apt install tree -y
sudo apt install ttf-mscorefonts-installer -y
sudo apt install unetbootin -y
sudo apt install virtualbox -y
sudo apt install vlc-plugin-fluidsynth -y
sudo apt install wakeonlan -y
sudo apt install wget -y
sudo apt install wine-stable -y
sudo apt install winetricks -y
sudo apt install winff -y
sudo apt install xfburn -y
sudo apt install xmp -y
sudo apt install xpaint -y
sudo apt install xsane -y
sudo apt install xterm -y
sudo apt install youtube-dl -y
sudo apt update
sudo apt upgrade
